[project]
id = "vk"
version = "0.7.0"
mach = "^6"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"
default = true

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt = 0
debug = true
simd = "scalarize"
vectorize = false
float_reassoc = false
default = true

[profile.release]
opt = 2
debug = false
simd = "scalarize"
vectorize = true
float_reassoc = false

[artifact.vk]
kind = "static"
entry = "lib/vk.mach"
out = "lib/vk"
targets = ["*"]
link = []
need = []
default = true

[dep.std]
git = "https://github.com/briar-systems/mach-std"
version = "^9.0"
