[project]
id = "vk"
name = "Mach Vulkan bindings"
description = "Mach Vulkan bindings"
version = "0.1.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[artifact.vk]
kind = "static"
entry = "vk.mach"
out = "lib/vk"
targets = ["*"]

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
